---
- name: Restart UFW
  service:
    name: ufw
    state: restarted

- name: Restart Fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Restart SSH
  service:
    name: ssh
    state: restarted
